In [2]:
# PyTorch: replacement for NumPy, deep learning platform

# Tensors
# similar to ndarrays, Tensors can be used on a GPU
# tensors are 'generalized' matrices, whereas matrices
# are 2D constructs, tensors can be 0d, 3d, etc

from __future__ import print_function
import torch

# construct 5x3 matrix
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00],
        [-1.0842e-19,  1.4569e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28],
        [ 1.4603e-19,  1.0899e+27,  6.8943e+34],
        [ 1.1835e+22,  7.0976e+22,  1.8515e+28]])


In [3]:
# construct randomly init matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.2569, 0.2591, 0.4653],
        [0.4692, 0.9818, 0.0423],
        [0.4468, 0.3776, 0.2474],
        [0.8321, 0.9620, 0.0350],
        [0.5335, 0.6356, 0.1639]])


In [4]:
# matrix filled with zeros of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# create a tensor based on an existing tensor
# these methods reuse properties from input tensor
# unless new values are provided
x = x.new_ones(5, 3, dtype=torch.double) #new_* takes size
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtpye
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3498, -1.0623,  0.6595],
        [-1.1913,  1.8088, -0.9358],
        [-0.5297, -0.1256,  1.2292],
        [-1.9324,  1.6949, -1.4049],
        [-1.8294, -1.7679, -0.9598]])


In [7]:
print(x.size()) #get its size (torch.Size is a tuple)

torch.Size([5, 3])


In [8]:
# OPERATIONS
y = torch.rand(5,3)
print(x+y)   # addition syntax 1

tensor([[ 0.8354, -0.8999,  1.6123],
        [-0.2731,  1.9293, -0.8929],
        [ 0.2396,  0.3262,  2.2153],
        [-0.9359,  2.2307, -1.2511],
        [-1.3797, -1.1937, -0.4320]])


In [9]:
print(torch.add(x, y)) # addition syntax 2

tensor([[ 0.8354, -0.8999,  1.6123],
        [-0.2731,  1.9293, -0.8929],
        [ 0.2396,  0.3262,  2.2153],
        [-0.9359,  2.2307, -1.2511],
        [-1.3797, -1.1937, -0.4320]])


In [10]:
result = torch.empty(5,3)
torch.add(x, y, out=result) #provide output tensor as arg
print(result)

tensor([[ 0.8354, -0.8999,  1.6123],
        [-0.2731,  1.9293, -0.8929],
        [ 0.2396,  0.3262,  2.2153],
        [-0.9359,  2.2307, -1.2511],
        [-1.3797, -1.1937, -0.4320]])


In [11]:
# addition in place (adds x to y)
y.add_(x)  # postfixed with _, changes y not x
print(y)

tensor([[ 0.8354, -0.8999,  1.6123],
        [-0.2731,  1.9293, -0.8929],
        [ 0.2396,  0.3262,  2.2153],
        [-0.9359,  2.2307, -1.2511],
        [-1.3797, -1.1937, -0.4320]])


In [12]:
print(x[:, 1])

tensor([-1.0623,  1.8088, -0.1256,  1.6949, -1.7679])


In [13]:
# reshape/resize tensor, use torch.view
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # size -1 inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# for one elmnt tensor, use .item() to get val as num
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7313])
0.7312920689582825


In [15]:
# NUMPY BRIDGE
# convert a torch tensor to numpy array and vice versa
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
# see how numpy array changed in value
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
# CONVERT NUMPY ARRAY TO TORCH TENSOR
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)  # changing the np array changed the tensor automatically
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
# CUDA TENSORS
# tensors can be moved by using the .to method
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) # .to can also change dtype

In [21]:
# PART 2 OF THE TUTORIAL
# AUTOGRAD: AUTOMATIC DIFFERENTIATION
# used for neural networds, autograd provides automatic
# differentiation for all ops on tensors

#TENSOR
# torch.Tensor is the central package
# .backward() : have all gradients computed , computes derivatives
#    if tensor is a scalar, don't need to specify args - if it has 
#    more than one element, you need to specify a gradient arg 
#    that has a matching tensor shape
# .grad : accumulates gradient from the tensor
# .detach() : detach a tensor from computation history,
#    prevents future computation from being tracked
# ** can also wrap a code block in 'with torch.no_grad()' to prevent
#    tracking history 

# Tensor and Function : interconnected acyclic graph, encodes history
# of computation, each tensor has a .grad_fun attrib that references
# a function that has created the Tensor

import torch

# create a tensor and set requires_grad=True to track it
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [22]:
# operation of tensor
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [23]:
# y created as a result of an op, so it has a grad_fn
print(y.grad_fn)

In [24]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [27]:
a = torch.randn(2, 2)
a = ((a*3) / (a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

False
True
tensor(515.7458, grad_fn=<SumBackward0>)


In [28]:
# GRADIENTS
# backprop because out contains single scalar

out.backward() #equivalent to out.backward(torch.tensor(1))
#print grads d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [30]:
x = torch.randn(3, requires_grad=True)

y= x*2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([ 0.8015,  0.0495, -1.1250], requires_grad=True)
tensor([  820.7128,    50.7310, -1152.0066], grad_fn=<MulBackward0>)


In [31]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [32]:
# stop autograd from tracking history

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
